[tool.black]
skip-string-normalization = false
include = '\.pyi?$'

[tool.isort]
profile = "black"                 # black-compatible (e.g., trailing comma)
known_first_party = ["pbench"]    # separate "pbench" section
multi_line_output = 3             # "hanging" indent with dedented paren
force_sort_within_sections = true # don't separate import vs from
order_by_type = false             # sort alphabetic regardless of case
